### PR TITLE
Boston's tests

### PR DESCRIPTION
**Pull request by bostonbragg**

### CODE REVIEW

**Comment by bostonbragg** [comment]
I'll fix the conflicts today or possibly tomorrow

**Comment by bostonbragg** [comment]
I'll also fix the "commenting everything out" issue

**Comment by bostonbragg** [comment]
Waiting on #20 to be merged in order to prevent further conflicts

**Review by eSuminski — APPROVED** [review]

**Comment by bostonbragg** [comment]
Will resolve any functional conflicts in a new pull request

**Comment by bostonbragg** [comment]
And I will also move the feature files back into their old folder, trying to do that in this pull request caused additional merge conflicts

**Review by wolfryan97 — APPROVED** [review]

**Pull request merged**
